### Creating ndarrays

In [1]:
data1 = [6, 7.5, 8, 0, 1]

In [2]:
import numpy as np
arr1 = np.array(data1)

In [3]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [5]:
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((2,3,2))

array([[[8.14085065e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.08886865e-037]],

       [[7.26086908e-043, 2.25293441e+184],
        [8.38583263e+169, 2.48879754e+180],
        [2.12815290e-052, 4.27556506e-033]]])

In [14]:
np.empty((2,3,3,2))

array([[[[ 2.45942334e+198,  3.09611470e+169],
         [ 7.26611038e+223,  3.46996985e-080],
         [ 1.35446683e+243,  1.23701654e-259]],

        [[ 1.63854572e+248,  4.78179653e+180],
         [ 1.05879251e-153,  4.26336324e+180],
         [ 1.02189320e-152,  6.20198208e+223]],

        [[ 2.19526581e-152,  1.81719791e+185],
         [ 5.98129759e-154,  3.80985847e+180],
         [ 6.01334668e-154,  4.47593816e-091]]],


       [[[ 6.01346953e-154,  2.59345432e+161],
         [ 2.46089539e-154, -7.67354944e-311],
         [ 1.96086583e+243,  6.01334434e-154]],

        [[ 1.06441859e+248,  4.47590761e-091],
         [ 6.01334512e-154,  7.12930994e+159],
         [ 2.61191759e+209,  6.01347002e-154]],

        [[ 1.38083749e+267,  9.80160104e-153],
         [ 3.17095859e+180,  4.70108004e+180],
         [ 1.13337591e-153,  7.20355552e+159]]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data types for ndarrays

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr = np.array([1, 2, 3, 4, 5])

In [19]:
float_arr = arr.astype(np.float64)

In [20]:
float_arr

array([1., 2., 3., 4., 5.])

In [21]:
arr ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

### Basic Indexing & slicing 

In [22]:
arr = np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[5]

5

In [25]:
arr[5:8]

array([5, 6, 7])

In [26]:
arr[5:8] = 12

In [27]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [28]:
old_values = arr.copy()

In [29]:
arr[1] = 10

In [30]:
arr

array([ 0, 10,  2,  3,  4, 12, 12, 12,  8,  9])

In [31]:
old_values

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### Boolean Indexing

In [32]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [33]:
data = np.random.randn(7,4)

In [34]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [35]:
data

array([[ 1.65010378, -1.30303881, -0.39210469,  0.29809103],
       [ 0.60196168,  0.52052151, -0.67126225, -0.50945809],
       [ 0.36755586,  0.47345492, -0.61150417, -0.41918278],
       [-1.63469997, -0.73329294,  0.34209828, -0.57518075],
       [ 0.18581654,  0.30846768,  0.4113955 , -0.31360593],
       [ 1.94509285,  2.50103577,  0.14775507, -1.04599287],
       [-0.73145306,  0.77082594, -0.44334774,  0.62222792]])

In [36]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [37]:
data[names == 'bob']

array([[ 1.65010378, -1.30303881, -0.39210469,  0.29809103],
       [-1.63469997, -0.73329294,  0.34209828, -0.57518075]])

In [38]:
data[names == 'bob', 2:]

array([[-0.39210469,  0.29809103],
       [ 0.34209828, -0.57518075]])

In [39]:
data[names == 'bob', 3]

array([ 0.29809103, -0.57518075])

In [40]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True])

In [41]:
data[~(names == 'bob')]

array([[ 0.60196168,  0.52052151, -0.67126225, -0.50945809],
       [ 0.36755586,  0.47345492, -0.61150417, -0.41918278],
       [ 0.18581654,  0.30846768,  0.4113955 , -0.31360593],
       [ 1.94509285,  2.50103577,  0.14775507, -1.04599287],
       [-0.73145306,  0.77082594, -0.44334774,  0.62222792]])

In [42]:
data[data < 0] = 0

In [43]:
data

array([[1.65010378, 0.        , 0.        , 0.29809103],
       [0.60196168, 0.52052151, 0.        , 0.        ],
       [0.36755586, 0.47345492, 0.        , 0.        ],
       [0.        , 0.        , 0.34209828, 0.        ],
       [0.18581654, 0.30846768, 0.4113955 , 0.        ],
       [1.94509285, 2.50103577, 0.14775507, 0.        ],
       [0.        , 0.77082594, 0.        , 0.62222792]])

In [44]:
data[names != 'joe'] = 7

In [45]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.60196168, 0.52052151, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.94509285, 2.50103577, 0.14775507, 0.        ],
       [0.        , 0.77082594, 0.        , 0.62222792]])

### Fancy Indexing

In [46]:
arr = np.empty((8,4))

In [47]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
for i in range(8):
    arr[i] = i

In [49]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [50]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [51]:
arr = np.arange(32).reshape((8,4))

In [52]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [53]:
arr[[1, 5, 7, 2],[0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [54]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing arrays and swapping axes

In [55]:
arr = np.arange(15).reshape((3,5))

In [56]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [58]:
arr = np.random.randn(6,3)

In [59]:
np.dot(arr.T, arr)

array([[11.95654149,  0.87242617,  3.09259051],
       [ 0.87242617,  4.8350231 , -0.54170629],
       [ 3.09259051, -0.54170629, 11.12374081]])

In [60]:
arr = np.arange(16).reshape((2,2,4))

In [61]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [62]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [63]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### Universal functions

In [65]:
arr = np.arange(10)

In [66]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [67]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [68]:
np.modf(arr)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Data Processing Using Arrays

In [69]:
points = np.arange(-5, 5, 0.01)

In [70]:
xs, ys = np.meshgrid(points, points)

In [71]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [73]:
arr = arr[arr>5]

In [75]:
arr.any()

True

In [76]:
arr.all()

True

In [77]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [78]:
np.unique(names)

array(['bob', 'joe', 'will'], dtype='<U4')

### File Input and Output with Arrays

In [79]:
arr = np.arange(10)

In [80]:
np.save('some_array', arr)

In [81]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.savez('array_archive.npz', a=arr, b=arr)